logging:
  level:
    root: warn
    com.example: info
    org.hibernate.type.descriptor.sql: trace
server:
  port: 8080
spring:
  profiles:
    active: main
    include:
      - db
      - login
      - aws
  # JSP ViewResolver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      # create(new table), update(add new column), none(nothing)
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul